#!/bin/bash
 #PBS -l nodes=2:ppn=16
 #PBS -l walltime=12:20:00
 #PBS -m a
 #PBS -M madcanda@iu.edu
 #PBS -N ping
 #PBS -q gpu
 #PBS_GPU_FILE gpuFile

 cd /N/u/madcanda/BigRed2/
 echo $(pwd)

 echo 'Start running!'
 module swap python/2.7.8 tensorflow/1.1.0
 
 cd ./Pong-v0/
 time aprun python main.py

 echo "Done!"
